# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split()

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
5*np.ones(10, dtype = 'int')

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [15]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
a = np.arange(9)
np.reshape(a, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [10]:
import pandas as pd

In [22]:
data=[]
pd.DataFrame(data, index=[0, 1, 2], columns=[0, 1])

0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [7]:
jan = [str(i)+'-01-2023' for i in range(1,32)]
feb = [str(i)+'-02-2023' for i in range(1,11)]
jan.extend(feb)
jan

['1-01-2023',
 '2-01-2023',
 '3-01-2023',
 '4-01-2023',
 '5-01-2023',
 '6-01-2023',
 '7-01-2023',
 '8-01-2023',
 '9-01-2023',
 '10-01-2023',
 '11-01-2023',
 '12-01-2023',
 '13-01-2023',
 '14-01-2023',
 '15-01-2023',
 '16-01-2023',
 '17-01-2023',
 '18-01-2023',
 '19-01-2023',
 '20-01-2023',
 '21-01-2023',
 '22-01-2023',
 '23-01-2023',
 '24-01-2023',
 '25-01-2023',
 '26-01-2023',
 '27-01-2023',
 '28-01-2023',
 '29-01-2023',
 '30-01-2023',
 '31-01-2023',
 '1-02-2023',
 '2-02-2023',
 '3-02-2023',
 '4-02-2023',
 '5-02-2023',
 '6-02-2023',
 '7-02-2023',
 '8-02-2023',
 '9-02-2023',
 '10-02-2023']

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [8]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [11]:
pd.DataFrame(lists, columns = ['Sr. No.', 'Name', 'Age'])

Sr. No. Name  Age
0        1  aaa   22
1        2  bbb   25
2        3  ccc   24